### ISSUE TITLE
limitations in the use of extra features

### ISSUE THREAD

**Issue by mims-b** [google/lightweight_mmm#273]
Hi I'm new to LMMM and modelling in general, I want to ask if there are limitations in what can be used as inputs for extra features (i.e. the control variables). For example can I have a column containing a continuous variable like "weekly average gas price" and then in another column have something like "holiday" which will be a binary variable and display 1 if there is a major holiday in that week and 0 if not. Thanks.

**Comment by becksimpson** [comment]
The only limitation for extra features is that they are modelled linearly, with a single multiplier coefficient, that has a zero-centered normal prior.

Due to the fact that intercept, media effects are constrained to be strictly positive. I think it can be especially important to ensure you're extra features are zero-centered or zero-minned during pre-processing, essentially just not have a large positive bias. As the lowest a lot of these other effects (paid media, intercept) can be is zero, as they are strictly positve (modelled with HalfNormals etc). So unlike a more un-constrained regression problem, they cannot enable negative offsets, so let's say gas price varies 2700 --> 2900, and that 200 change caused a 20% change in target (~0.2), suddenly to capture that effect, you would have to create a positive bias, ~2.7, which couldn't possibly be offset, as there are no negative learned contributors to do so. So the impact of gas price variation could not be learned. As you probably know it is usually good to do this sort of pre-processing in any problem, it's just in this model form, we go from "this might worsen model convergence, fit, make it take longer etc)" to "there is no way the model could model this"

In addition extra features should not appear in the causal chain anywhere between advertisement and target impact, or you'll be cannibalising credit. An example would be your target is sales. A bad extra feature would be activity on your website, clicks, items added to basket, as a lot of these activities would have been driven by media advertisement up the chain. The two examples you gave are good, gas price and holiday.

**Comment by mims-b** [comment]
Hi @becksimpson, thanks for your message. I don't fully understand the contents of the second paragraph but this is my interpretation and please correct me where wrong (in the example below, I will use sales of ready-made meals as my target).

- The lowest values the intercept and "effects of media channels" can take, is zero
- The "effects of media channels" are modelled to only be positive i.e. if sales is our target then the media spend can't lead a drop in sales
- The control variables (or extra features) we use are also only modelled to have a positive effect on sales. Therefore if a control variable e.g. gas price contributed to a reduction in sales of ready-made meals then we want the "positive effect" to be minimised. We can do this by making sure the extra features are zero centered or zero minned.

Thanks for your time.

**Comment by mims-b** [comment]
Many thanks for the explanation, all clear now.
