### ISSUE TITLE
Can't install LightweightMMM - Error on jaxlib

### ISSUE THREAD

**Issue by federicoteti6** [google/lightweight_mmm#6]
hi,
I'm trying to install the lightweight_mmm library but it gives me the following error:
```
ERROR: Cannot install lightweight-mmm == 0.1.1 and lightweight-mmm == 0.1.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    lightweight-mmm 0.1.2 depends on jaxlib> = 0.3.0
    lightweight-mmm 0.1.1 depends on jaxlib> = 0.3.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

how can i solve?
I use windows and the python version is 3.8.13.
I tried to install jaxlib with pip install but the result was this:
```
ERROR: Could not find a version that satisfies the requirement jaxlib (from versions: none)
ERROR: No matching distribution found for jaxlib
```

another test was installing jax [cpu]:
```
pip install --upgrade "jax [cpu]"
```
but the result hasn't changed

**Comment by pabloduque0** [comment]
Hello @federicoteti6 ! Thanks for reporting this!

The JAX support for Windows is limited ([see the open JAX issue](https://github.com/google/jax/issues/438)). Not sure how well it is working but I am aware of [jax-windows-builder](https://github.com/cloudhan/jax-windows-builder), might be worth giving it a try.

Otherwise I would recommend running it from Linux if it is possible to you. Or you can also run it on [Colab](https://colab.research.google.com/) if you dont have access or dont want to use Linux.

**Comment by federicoteti6** [comment]
thanks, colab works and will use that

**Comment by ritahoang94** [comment]
I have the same error message as @PoromenoC96 . For me the message appears when I tried to import arviz library. Please someone let me know how to fix this.
