### ISSUE TITLE
Reproduce response curves from a previous model

### ISSUE THREAD

**Issue by l-d96** [google/lightweight_mmm#65]
Hi!

First of all, thank you for this amazing package!

I've built a multilinear regression model (frequentist, no Bayes) using this transformation for the data:
 beta * (1 - exp(-x / slope))
where beta here is the media coefficients.

I want to transition from this model to a bayesian framework using your package. I am using the hill_adstock model, where I am using the betas I found with the linear regression as media priors, and the slope found with the linear regression as half_life priors. I am setting the slope of the Hill function to a HalfNormal with 0.5 scale.

My goal here would be to get the response curves of the bayesian model as close as possible to the response curves of my previous model, so that I can then use the posteriors I get from the bayesian model as priors for a new bayesian mmm with new data.

My understanding is that the media priors are the scale of a HalfNormal distribution, whose samples are the coefficients of the media activity terms in the model: so it should regulate the height of the response curve.

Half life instead determines the point at which the response curve is at half its maximum, so it should control the uplift, or how rapidly the curve increases.

The slope should determine the shape of the curve, so setting it to < 1 gets us a shape more like the upper half of a C, rather than an S shaped curve.

I've been trying with different prior distributions, even changing the media prior distribution in models.py to a normal distribution centered on those beta values, however the shape of the response curves is unpredictable and I cannot get it close to my original response curves. 

Do you have any suggestions on how to go about this? Am I interpreting the parameters wrong?

Again, thanks a lot for your work!

**Comment by pabloduque0** [comment]
Hello @l-d96 !

Yes, I guess trying to get very similar response curves to a previous model can be tricky, specially if the transformations you had were not the exact same.

Overall I think you are on the right track by altering the priors of the `hill-adstock`, so `lag_weight`, `slope` and `half_max_effective_concentration`. If your LMMM model is saturating too much you can always try the `carryover` or `adstock` models which have exponent for saturation and that tends to lead to less saturation, and play with the respective priors there [See all here](https://lightweight-mmm.readthedocs.io/en/latest/custom_priors.html).

The media priors wont affect the response curves though, so you can focus on the rest (transformations are applied before and the dot product by the coefficients is after all linear). However changing the beta medias will change how all parameters are sampled indirectly so you could end up with different outputs due to that. I think for what you are trying to achieve I would keep them fixed (at whatever values you want) and use the others to try to get the response curves to fit your expectations.

Hope it helps!
