### ISSUE TITLE
Time varying behavior for media coefficients.

### ISSUE THREAD

**Issue by sataksipagat13** [google/lightweight_mmm#81]
Hi,

I have a question that most likely you think about that along the way. I want to include time-varying behavior for media coefficients.  Probably, the most straightforward way  is for this using GaussianRandomWalk. What is your opinion about that ? Because my media channels show different performances on different times and I want to see that difference directly.

**Comment by pabloduque0** [comment]
Hello @sataksipagat13 !

At the moment we dont offer time varying coefficients out of the box, but it is something we have in mind for the mid-term. So you would have to make quite a few changes to the code for it in order to work. From the modelling point of view is not much, but most plots/insights functions would need to deal with an extra dimension on those parameters.

Essentially it would require the main points:
- Adding an extra dimension to the media parameters when sampling them.
- Then you would have to adapt the plots and insights functions to deal with that extra dimension.

Hope it helps!

**Comment by sataksipagat13** [comment]
Thank you so much. I will try to implement it and let you know !

**Comment by itaher-aclu** [comment]
Hi I am following up on this closed ticket. I am wondering if:

* @sataksipagat13 has experimented with updating the package to leverage time varying coefficients. If so what was the result
* @pabloduque0 has any further details about including this officially into the package. Something like a rough timeline would be helpful
